### ISSUE TITLE
Add documentation for running Dataflow on Flink on a cluster

### ISSUE THREAD

**Issue by slnovak** [dataArtisans/flink-dataflow#4]
Hi,

The README states that you can run Dataflow on Flink. Is it possible to provide some additional details on how to accomplish this?

Thanks!

**Comment by rmetzger** [comment]
Hi,
thank you for opening the issue. The main author of the flink-dataflow integration is currently on vacation. He'll be back next Monday.

Without having looked into details, I think you can execute a flink-dataflow program on a cluster as follows:
- Add the maven-assembly-plugin to your maven project so that it builds a fat (or uber) jar. You'll find plenty of advise how to do this on the web.
- build a fat jar
- submit the fat jar to a Flink cluster using `/bin/flink run <fatJar>`.

You can try this out locally as well by starting a flink cluster with the `./bin/start-local.sh` script. On localhost:8081, you'll find a web interface of Flink.

**Comment by mxm** [comment]
Hi @slnovak, thanks for opening the issue. I'll update the README to include more information about how to run a Dataflow job on a Flink cluster. @rmetzger already presented the essential steps. Did that help you? I'll elaborate on the steps in the updated README.

**Comment by slnovak** [comment]
Thanks @rmetzger and @mxm! I'll give that a shot and see if I can get it up and running. :beers:

**Comment by mxm** [comment]
@slnovak I've updated the README to explain the necessary steps.
